name: CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Emacs ${{ matrix.emacs_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '25.1'
          - '26.1'
          - '27.1'
          - '28.1'
          - '29.1'
          - 'snapshot'

    steps:
      - uses: actions/checkout@v3

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - run: make test
